# fly.toml app configuration file for Fly.io multi-region stateless frontend

app = "pages-app-l-ykfg"
primary_region = "bom"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"      # Stop machines when idle
  auto_start_machines = true       # Start on demand (autoscaling)
  min_machines_running = 0         # Zero when no traffic
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[experimental]
  auto_rollback = true             # Auto rollback if a deployment fails

[scale]
  min = 0
  max = 3                          # Allow autoscaling up to 3 per region
